Algoritmo "array_tabela"
Var
   list: vetor [0..2, 0..2]de caractere
Inicio
      list [0, 0] <- ("Grêmio")
      list [0, 1] <- ("São Paulo")
      list [0, 2] <- ("Palmeiras")
      list [1, 0] <- ("Milan")
      list [1, 1] <- ("Barcelona")
      list [1, 2] <- ("Juventus")
      list [2, 0] <- ("Ajax")
      list [2, 1] <- ("Liverpool")
      list [2, 2] <- ("Real Madrid")
      Escreval (" Jogo de hoje: ",list [0, 0]," X ", list [2,0])
Fimalgoritmo