Algoritmo "somaEnquantoFacaImproved"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
   soma, valorinfo: real
Inicio
      soma <- 0
      valorinfo <- 10000
      enquanto valorinfo <> 0 faca
            Escreval("Informe um valor para o cálculo")
            Leia (valorinfo)
            soma <- soma + valorinfo
            Escreval ("Total: ", soma)
      fimenquanto
Fimalgoritmo