Algoritmo "MatrizNúmeros"
Var
   matriznum : vetor [1..3,1..3] de caractere
   y, x, soma : inteiro
Inicio
      para y de 1 ate 3 faca
           para x de 1 ate 3 faca
                escreval("Entre com os dados")
                Leia (matriznum [x,y])
           fimpara
      fimpara

      para y de 1 ate 3 faca
           para x de 1 ate 3 faca
                Escreva (matriznum [x,y]
           fimpara
           Escreval ("")
      fimpara

Fimalgoritmo
